### PR TITLE
Created a code of conduct

### PR DESCRIPTION
**Pull request by ghost**
This will be useful and good to have when we add more team members to the GitHub organization.

### CODE REVIEW

**Review by Redleg281 — APPROVED** [review]
Okay

**Comment by ethanchoo** [comment]
Sure, new people would be useful, because right now, it takes me 1-4 hours to recreate a character (depending on how difficult that character is to recreate). That as well as doing other things in my life can take a lot of time for one person.

**Review by ethanchoo — APPROVED** [review]
Sure.

**Review by ghost — DISMISSED** [review]
@CameronSamuels: In "Our Pledge" change the wording of "body size" to "physique". This wording would fare better with a more sensitive topic such as this.

**Comment by ghost** [comment]
I agree. I will do this in my next commit.

**Comment by CooperLan** [comment]
Good idea

**Review by ghost — APPROVED** [review]
Looks good! Thanks! Go for it. If anything else comes to mind, I'll just comment it.

**Comment by ghost** [comment]
I will wait for @CooperLan

**Comment by ghost** [comment]
I will merge this now. We can make changes if @CooperLan needs them.

**Comment by ghost** [comment]
Alright that works

**Pull request merged**
