### PR TITLE
(issue)Balanced endless mode earnings

### PR DESCRIPTION
**Pull request by ghost**
Made a maximum of 800 redbacks for a user to earn in a single endless mode series.

This is good so people can't get an insane amount of redbacks.

This resolves issue #103.

@ethanchoo, @VishwamR, @stonejess, Is a maximum of 800 redbacks a good amount for the maximum amount you can earn in a single endless mode game? If not, what else do you think?

### CODE REVIEW

**Comment by VishwamR** [comment]
We have to raise this when campaign mode is added

**Comment by ghost** [comment]
@VishwamR, this is endless mode by the way, not campaign mode. These restraints only apply to endless mode. Does that solve the problem now? Or am I not getting something?

**Comment by VishwamR** [comment]
If there is a limit that low when you try to upgrade later on it'll get too
hard to upgrade your characters. That's essentially putting a cap on the
the stat increase so later in campaign mode you'll get stuck on a certain
lvl

>

**Comment by ghost** [comment]
Well isn't that challenging? If you think it is too challenging, how about 1,000?

**Comment by ghost** [comment]
But also, harder campaign levels can give higher rewards.

**Comment by VishwamR** [comment]
We should make it so that it automatically ends after you reach the cap off 800

**Comment by VishwamR** [comment]
How bout 1500

**Comment by ghost** [comment]
I don't think we need it to end when they reach it because they can continue to play and have fun. Right?

1500 seems ok. That might work. I will change it to 1500.

**Comment by ghost** [comment]
Ok so I made it a max of 1,500.

Do you get what I mean for not stopping them when you get the max. Wouldn't it be mean to cut them off from playing when they get the max. Isn't that kind of harsh. I think they should play as long as they want to and not be cut off. Also, it would be cool to see how many times you clicked and how long you spent playing (the stats). And also, if we don't cut them off, we can get analytics showing, "wow this person played endless mode for 20 minutes." Right?

**Comment by VishwamR** [comment]
What about a notification.

You have reached the max amount of possible redbacks.

In the top left corner. It slides in and then slides out. Because some
people are only doing it for the redbacks

>

**Comment by ghost** [comment]
That sounds great, @VishwamR! I will implement this great idea. Thanks!

**Comment by VishwamR** [comment]
To approve this do I need to check for the cap off and the notification or just the cap off

**Comment by ghost** [comment]
You can approve both once I add the notification.

**Review by VishwamR — APPROVED** [review]

**Comment by ghost** [comment]
Wait, so @VishwamR, you want me to merge this now, and create a separate pr for the notification?That's not what we decided to do, but I do think that would be better. So should I merge?

**Comment by VishwamR** [comment]
K

>

**Pull request merged**
