### PR TITLE
(issue)Added stats icons

### PR DESCRIPTION
**Pull request by ghost**
This resolves issue #159

This adds the icons for the stats to be used in the new store (attack, healing, and health icons)

These were made by @ethanchoo and edited by @cameronsamuels

### CODE REVIEW

**Comment by VishwamR** [comment]
Where do I view the stats

**Comment by ghost** [comment]
[Attack](https://github.com/thebclickteam/bocracy/pull/169/files?short_path=308bc56#diff-308bc5620a010a8b23014fa4050be353) - [Health](https://github.com/thebclickteam/bocracy/pull/169/files?short_path=e42e929#diff-e42e929b9ae5583e95eddd37942e1dca) - [Healing](https://github.com/thebclickteam/bocracy/pull/169/files?short_path=1a7650f#diff-1a7650f0ed53adefc28cde7a4c8322a0)

**Comment by VishwamR** [comment]
On the preview

**Comment by VishwamR** [comment]
On the preview website

**Comment by ghost** [comment]
They aren't on it yet, just on the files on the website (not used yet)

**Review by ethanchoo — APPROVED** [review]

**Pull request merged**
