### PR TITLE
(issue)Added an inventory bar to the store

### PR DESCRIPTION
**Pull request by ghost**
This inventory bar will allow people to know how much redbacks they have.

This is a needed feature because a game never does not tell people how much currency they have.

This resolves issue #196.

### CODE REVIEW

**Comment by VishwamR** [comment]
Btw that's a double negative
Also how bout we move it above the area back button

**Comment by VishwamR** [comment]
Over there it looks like the cost of the character

**Comment by ghost** [comment]
@VishwamR, where it is now is the only place it can fit, plus, I don't think it will be too confusing for the user. It doesn't say purchase, and the actual purchase button says purchase above.

**Review by VishwamR — APPROVED** [review]
K

**Pull request merged**
