### PR TITLE
Removed tap highlight color

### PR DESCRIPTION
**Pull request by ghost**
This removes the blue or gray color when clicking a button or image.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Looks fine. All that was changed was adding the transparent tap color which was the purpose.

**Review by ghost — COMMENTED** [review]
Looks fine. All that was changed was the tap color which was he purpose.

**Review by ghost — COMMENTED** [review]
Looks fine. All that was changed was adding the transparent tap color which was the purpose.

**Review by ghost — COMMENTED** [review]
Everything is reordered due to a different minifier, but works fine and is the same.

**Review by ghost — COMMENTED** [review]
Everything is reordered due to a different minifier, but works fine and is the same.

**Review by ghost — COMMENTED** [review]
Everything is reordered due to a different minifier, but works fine and is the same.

**Review by ghost — COMMENTED** [review]
Looks fine. All that was changed was just being merged from 'master'. All works just like it is supposed to be after merged.

**Comment by ghost** [comment]
Everything looks fine. You need to review, @faithtsang.

**Comment by faithtsang** [comment]
Alright, it all looks good, go for it

**Review by ghost — APPROVED** [review]
I think it's fine, go for it

**Pull request merged**
