### PR TITLE
Landing page animations

### PR DESCRIPTION
**Pull request by ghost**
These animations include a moving background, click effects for switching battleground selection in the series mode setup screen, fading in and out when changing view of either the play now button or not enough button in the series mode setup screen, and the best for last: animations when choosing series mode characters.

See the preview on our alpha site at <http://bocracy.bitballoon.com> or look at this GIF preview:

preview

### CODE REVIEW

**Review by Redleg281 — APPROVED** [review]
That looks cool

**Review by ghost — COMMENTED** [review]
This should've said "Added click effects to battleground buttons"

**Review by ethanchoo — APPROVED** [review]
The animation looks great!

**Comment by ghost** [comment]
Thank you! I will merge this now.

**Pull request merged**
