### PR TITLE
(issue)Recoded battle backgrounds

### PR DESCRIPTION
**Pull request by ghost**
- Made body have the battle background instead of the sections
- Removed the shifting of the battle backgrounds
- Removed fallback colors of the buttons and the sections
- Randomized x-position of the background on battle start

This resolves issue #223 and #225.

### CODE REVIEW

**Comment by ghost** [comment]
@xeleration/bocracy, make sure this works on the test deploy preview and then review.

**Comment by VishwamR** [comment]
I can't access the test preview

**Comment by ghost** [comment]
Yeah, I can't seem to either. It seems there was an error because it currently says, "Waiting for status to be reported."

I'll look into it.

**Comment by ghost** [comment]
Try this link, https://5a9877220b79b72b458729da--bocracy.netlify.com/

**Comment by ghost** [comment]
This needs to be merged soon, but it requires some editing first. I’ll try to work on it today

**Pull request merged**
